#!/usr/bin/env bash

# docker volume create --name=beanstalk

docker_bin="$(which docker 2> /dev/null)"

${docker_bin} run -d \
    -p 127.0.0.1:11300:11300 \
    -v beanstalk:/var/lib/beanstalkd \
    phalconphp/beanstalkd "$@"
